---
title: "Performances"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---


```{r perf-setup, include = FALSE, eval = TRUE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
source("Scripts/00_setup.R")

library(viridis)

```


```{r perf-load-model, echo = FALSE, results='hide'}
load("../Data/models/R_hsmm.Rdata", verbose = TRUE)
```


# Performances

## On Synthetic data

__Loading and formatting results__

```{r perf-load-synth-data}
X = read_feather("../Data/synthetic_data/Xsim.feather")
RES = read_feather("../Data/decodings/RES_synthetic_data.feather")
```


```{r perf-format-synth-data}

XP = full_join(RES, X %>%  select(seq_id, t, state, tracking_category, alpha) %>% rename(state_GT = state), by = c("seq_id", "t"))

```


__Overall accuracy__


```{r perf-synth-accuracies}

Accuracies = XP %>%  
  group_by(alpha, tracking_category) %>% 
  summarize(Accuracy = mean(state == state_GT, na.rm = TRUE),
            Weighted_Accuracy = weighted.mean(x = state == state_GT, w = prob, na.rm = TRUE),
            .groups = "drop") %>% 
  pivot_longer(cols = c("Accuracy","Weighted_Accuracy"), names_to = "accuracy_type", values_to = "Accuracy") %>% 
  mutate(accuracy_type = accuracy_type %>%  str_replace(., "_"," "))

```


```{r perf-synth-accuracies-viz, echo = FALSE, fig.height=3, fig.width=8, fig.cap="Accuracy on synthetic data."}

g_synth_acc = 
  ggplot(Accuracies, 
       aes(x = factor(alpha, levels = sort(unique(alpha))) %>% as.numeric(), y = Accuracy, col = tracking_category)) + 
  geom_vline(xintercept = 4, color = "gray") +
  geom_point() + geom_line() + facet_grid(. ~ accuracy_type) + 
  ylab("") + xlab(expression(alpha)) + 
  scale_color_manual(name = "Tracking category", values = viridis_pal(direction = -1, option = "D")(4)) + 
  scale_y_continuous(breaks = seq(0,1,by = 0.2)) +
  scale_x_continuous(breaks = 1:length(unique(Accuracies$alpha)), labels = sort(unique(Accuracies$alpha)), minor_breaks = NULL)

g_synth_acc

save(g_synth_acc, file = "../Data/plots/g_synth_acc.Rdata")

```

__State-specific accuracy__


```{r perf-synth-state-accuracies}

Accuracies_per_state = XP %>% group_by(alpha, tracking_category, state_GT) %>% 
  summarize(Accuracy = mean(state == state_GT, na.rm = TRUE),
            Weighted_Accuracy = weighted.mean(x = state == state_GT, w = prob, na.rm = TRUE),
            .groups = "drop") %>% 
  mutate(state_name = R_hsmm$state_names[state_GT] %>% factor(., levels = R_hsmm$state_names),
         state_col = R_hsmm$state_colors[state_GT]) %>% 
  pivot_longer(cols = c("Accuracy","Weighted_Accuracy"), names_to = "accuracy_type", values_to = "accuracy") %>% 
  mutate(accuracy_type = accuracy_type %>%  str_replace(., "_"," "))

```

```{r perf-synth-state-accuracies-viz, echo = FALSE, fig.height=5, fig.width=6, fig.cap="Per state accuracy on synthetic data."}

g_synth_acc_per_state = 
  ggplot(Accuracies_per_state %>% filter(state_name %in% c("M", "O", "P", "L", "B")) , 
       aes(x = factor(alpha, levels = unique(alpha)) %>%  as.numeric(), y = accuracy, col = tracking_category)) +
  geom_vline(xintercept = 4, color = "gray") +
  geom_point() + geom_line() + 
  facet_grid(state_name ~ accuracy_type) + 
  ylab("") + xlab(expression(alpha)) + 
  scale_color_manual(name = "Tracking category", values = viridis_pal(direction = -1, option = "D")(4)) + 
  scale_y_continuous(breaks = seq(0,1,by = 0.2)) +
  scale_x_continuous(breaks = 1:length(unique(Accuracies$alpha)), labels = sort(unique(Accuracies$alpha)), minor_breaks = NULL)


g_synth_acc_per_state


save(g_synth_acc_per_state, file = "../Data/plots/g_synth_acc_per_state.Rdata")


```

```{r perf-synth-state-accuracies-viz-2, echo = FALSE, fig.height=5, fig.width=6, fig.cap="Per state accuracy on synthetic data."}

g_synth_acc_per_state2 = 
  ggplot(Accuracies_per_state %>% filter(state_name %in% c("M", "O", "P", "B"), accuracy_type == "Weighted Accuracy") , 
       aes(x = factor(alpha, levels = unique(alpha)) %>%  as.numeric(), y = accuracy, col = tracking_category)) +
  geom_vline(xintercept = 4, color = "gray") +
  geom_point() + geom_line() + 
  facet_grid(. ~ state_name) + 
  ylab("") + xlab(expression(alpha)) + 
  scale_color_manual(name = "Tracking category", values = viridis_pal(direction = -1, option = "D")(4)) + 
  scale_y_continuous(breaks = seq(0,1,by = 0.2)) +
  scale_x_continuous(breaks = 1:length(unique(Accuracies$alpha)), labels = sort(unique(Accuracies$alpha)), minor_breaks = NULL)

g_synth_acc_per_state2

save(g_synth_acc_per_state2, file = "../Data/plots/g_synth_acc_per_state2.Rdata")

```



__Confusion matrices__



```{r perf-synth-conf-mat}

confusion_matrix_df = XP %>% 
  filter(!is.na(state)) %>% 
  group_by(alpha, tracking_category, state_GT, state) %>% 
  summarize(n = n(),
            wn = sum(prob),
            .groups = "drop") %>% 
  group_by(alpha, tracking_category, state_GT) %>% 
  mutate(tot = sum(n),
         wtot = sum(wn),
         .groups = "drop") %>% 
  ungroup() %>% 
  mutate(perc = n/tot,
         wperc = wn/wtot) %>% 
  select(-n, -wn, -tot, -wtot) %>% 
  pivot_longer(cols = c("perc","wperc"), names_to = "type", values_to = "fraction") %>% 
  mutate(type = ifelse(type == "perc", "Accuracy","Weighted Accuracy"),
         GT_state_name = R_hsmm$state_names[state_GT] %>%  factor(., levels = R_hsmm$state_names),
         decoded_state_name = R_hsmm$state_names[state] %>%  factor(., levels = R_hsmm$state_names))

```

```{r perf-synth-conf-mat-viz, fig.width=15, fig.height=12, fig.cap="Confusion matrix for the decoding on synthetic data."}

g_synth_conf_mat = 
  ggplot(confusion_matrix_df %>%  filter(type == "Accuracy"),
       aes(x = decoded_state_name, y = GT_state_name, fill = fraction))+
  geom_tile()+
  scale_y_discrete(drop = FALSE) +
  facet_grid(tracking_category ~ alpha) +
  scale_fill_gradient(low = "white", high = "steelblue4", limits = c(0,1)) +
  coord_fixed() +
  ylab("Simulated states (ground truth)") + xlab("Decoded states") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

g_synth_conf_mat

save(g_synth_conf_mat, file = "../Data/plots/g_synth_conf_mat.Rdata")

```




\newpage

## On Kindara data

Loading data and formatting results

```{r perf-real-loading-data}

X = read_feather(path = paste0(IO$output_data, "processed_app_data.feather"))
RES = read_feather(path = paste0(IO$output_data, "RES_app_data.feather"))
ML = read_feather(path = paste0(IO$output_data, "ML.feather"))

```


```{r perf-real-ML-XP}

ML = ML %>% rename(state_GT = state) 

XP = full_join(X, RES, by = c("seq_id", "t")) %>% 
  left_join(., ML, by = c("seq_id", "t") ) 

write_feather(XP, path = paste0(IO$output_data, "decoding_results_app_data.feather"))

```

__Overall accuracy__


```{r perf-real-Accuracies}

Accuracy = mean(XP$state == XP$state_GT, na.rm = TRUE)
Accuracy

Weighted_Accuracy = weighted.mean(x = XP$state == XP$state_GT, w = XP$prob, na.rm = TRUE)
Weighted_Accuracy


```

__Confusion matrices__

```{r perf-real-conf-mat}

confusion_matrix_df = XP %>% 
  filter(!is.na(state), !is.na(state_GT)) %>% 
  group_by(state_GT, state) %>% 
  summarize(n = n(),
            wn = sum(prob),
            .groups = "drop") %>% 
  group_by(state_GT) %>% 
  mutate(tot = sum(n),
         wtot = sum(wn),
         .groups = "drop") %>% 
  ungroup() %>% 
  mutate(perc = n/tot,
         wperc = wn/wtot) %>% 
  select(-n, -wn, -tot, -wtot) %>% 
  pivot_longer(cols = c("perc","wperc"), names_to = "type", values_to = "fraction") %>% 
  mutate(type = ifelse(type == "perc", "Accuracy","Weighted Accuracy"),
         GT_state_name = R_hsmm$state_names[state_GT] %>%  factor(., levels = R_hsmm$state_names),
         decoded_state_name = R_hsmm$state_names[state] %>%  factor(., levels = R_hsmm$state_names))
```


```{r perf-real-conf-mat-viz, fig.width=10, fig.height=4.5, fig.cap="Confusion matrix between manually labelled and decoded states."}

g_conf_mat = ggplot(confusion_matrix_df, aes(x = decoded_state_name, y = GT_state_name, fill = fraction)) +
  geom_tile() + 
  facet_grid(. ~ type) +
  scale_fill_gradient("State-specific accuracy", low = "white", high = "steelblue4", limits = c(0,1)) +
  coord_fixed() +
  ylab("Manually labelled states") + xlab("Decoded states")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

g_conf_mat

save(g_conf_mat, file = "../Data/plots/g_conf_mat.Rdata")
  
```



__Decoded sequences__

```{r perf-real-sequences, warning = FALSE, fig.width=10, fig.height=3}

ordered_sequences =
  XP %>% 
  group_by(seq_id) %>% 
  filter(seq_id %in% unique(RES$seq_id),
         !is.na(state_GT)) %>% 
  summarize(
    n_wrong = sum(state != state_GT),
    accuracy = mean(state == state_GT),
    .groups = "drop"
  ) %>% 
  arrange(-n_wrong)

for(i in 1:10){ # nrow(ordered_sequences) # length(unique(RES$seq_id))
  uid = ordered_sequences$seq_id[i]  # unique(RES$seq_id)[i]
  this_user_XP = XP %>% filter(seq_id == uid) %>% 
    rename(state_decoded = state,
           state_prob_decoded = prob)
  
  plot_hsmm_seq(X = this_user_XP, model = R_hsmm, title = uid,
                compact_view = TRUE, 
                add_color_legend_in_compact_view = FALSE) %>%  
    print() 

}




```



