---
title: "Introduction"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---


```{r intro setup, include = FALSE, eval = TRUE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
source("Scripts/00_setup.R")
```

# Introduction

Menstrual cycle and fertility tracking apps have become increasingly popular and are now used by millions of women worldwide, generating very large datasets of self-reports related to the menstrual cycle and reproductive events. These large datasets potentially hold information which can be used to tackle scientific challenges and address unanswered question on the reproductive biology in humans. 

[Examples].

At an individual level, these apps can be used to affordably and prospectively collect longitunal data of menstrual-health related body signs and symptoms, which can then be 

A first challenge towards using these self-reported data for such questions is to contextualize the each observation in the reproductive time-line of a user. The interpretation of a reported symptom may indeed be very different if a user is pregnant or going through a long anovulatory phase.

Such contextualization can be done by anotating the users' time-series with biologically-relevant labels reflecting our current knowledge of the menstrual cycle and reproductive events. 

Such labelling process can however be challenging on self-tracked datasets as missing data are a common concern. Few time-series analysis methods have been so far design to deal with multi-modal observation with lots of missing datapoint. 

[More about Markov and semi-Markov models].

Here, we modify the existing `mhsmm` package to allow for missingness patterns that may differ between observations (i.e. missing time-points are not shared between the different tracked feature) and used this modified semi-Markov framework to decode timeseries of fertility app users.


[Expand]

Main modifications:

- Allowing for any pattern of data missingness

- Confidence score

- Allowing for multi-variate time-series in which each variable may be described by different distribution families.

- (Re-computing the emission parameters only for observed states).


## Methods

We use a sub-set (114 users) of all users' time series to test and improve different decoding methods and compare them.

Currently implemented methods:

- baseline: rule-based decoding (if-else statements)

- semi-Markov: decoding with initial model parameters

- semi-Markov: decoding with fitted model parameters

- (to come) decoding using a deep-learning approach



## Workflow

Preparation:

1. Data pre-processing (in a separate file - see github repo)

2. Manual labelling and validation of user's time-series (via a standalone shiny app)

***

Actual decoding:

1. Specification of the Model: Architecture and Initialization of the Model's parameters

    + States (defined manually, informed by biology)
  
    + Initial probabilities (defined manually, more likely to start on a period)
  
    + Transition probabilities (defined manually, mostly set the architecture of the transitions)
  
    + Sojourn (For some "artificial states", sojourn are set manually to reflect 1 or 2-days states; for the other states, they are fitted from previous results and/or informed by biology)
  
    + Emission probabilities (initially defined manually; compared with the observation values in the manually labelled time-series and adjusted if needed)
    
    
2. Model fitting (EM with interactive boosting)  

    + Decode time-series with initial model; compute accuracy on parts with manual labels (`A_i`: Accuracy with initial parameters)
    
    + Interactive Boosting: Manually validate the time-series that are properly decoded; manually label the parts of the time-series that are not properly decoded.
    
    + Fit the model and decode the time-series with the fitted model; compute the accuracy on parts with manual labels (`A_f`: Accuracy with fitted parameters) and compare `A_f` with `A_i`.


3. Decoding of the time-series with the fitted parameters.

    + Decoding algorithm 1 : "Smoothed" (i.e. backward-forward) - provides the probability of each state at each time-point
  
    + Decoding algorithm 2 : "Viterbi" - provides the most likely sequence



