---
title: "Fix labels after changes in model specifications"
author: "Laura Symul"
date: "1/9/2020"
output: html_document
---



```{r}
labels = read_feather(path = paste0(IO$output_data, "manual_labels.feather"))
```


# "Pregnancy with birth" got split into the 3 trimesters


```{r}

labels$key = paste0(labels$user_id, "_", labels$rel_date)
labels = labels %>%  arrange(key)

k = which(labels$state_name == "Pregnancy with Birth")
if(length(k)>0){
  label_ids = unique(labels$label_id[k])
  for(label_id in label_ids){
    j = which(labels$label_id == label_id)
    labels$state_name[j[1:min(length(j),12*7)]] = "Pregnancy with Birth - 1st trimester"
    if(length(j)>12*7){labels$state_name[j[(12*7+1):min(length(j),2*12*7)]] = "Pregnancy with Birth - 2nd trimester"}
    if(length(j)>2*12*7){labels$state_name[j[(2*12*7+1):length(j)]] = "Pregnancy with Birth - 3rd trimester"}
  }
}

```

# State colors got changed

```{r}
labels$color = hsmm$states$colors[match(labels$state_name, hsmm$states$names)]
```




# Save


```{r}
write_feather(labels, path = paste0(IO$output_data, "manual_labels.feather"))
```

