---
title: "Figures"
author: "Laura Symul"
date: "12/9/2020"
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

library(knitr)
library(kableExtra)
library(tidyverse)
library(feather)
library(magick)
library(HiddenSemiMarkov)
library(ggplot2)
library(ggpubr)


source("Scripts/00_setup.R")

```


```{r loading-actual-data, echo = FALSE}

XP = read_feather(
  path = "../../semiM-Data/Kindara/output_data/decoding_results_app_data.feather")

```

# Figure 1

```{r fig1, fig.width = 12, fig.height = 6}

# app log screen
K_screen = image_read("../../semiM-Public-Repo/Figures_Tables_Media/Media/kindara_screen.png")

K_screen_ratio = image_info(K_screen)$height / image_info(K_screen)$width 
padding = 20

g_app_screen = 
  ggplot() + 
  coord_fixed(ratio = K_screen_ratio) +
  background_image(K_screen) +
  theme(plot.margin = ggplot2::margin(t=padding, l=padding, r=padding, b=padding, unit = "pt"))


# time-series examples
load("../../semiM-Public-Repo/Data/models/R_hsmm.Rdata")
X = read_feather("../../semiM-Data/Kindara/output_data/processed_app_data.feather")

selected_users = c("0ccf07c0da86d9fda79524c1e771df35b529ec7e", "ee6255ac9d3ef19f22750b1e8b3e7e42d2b5742c")

plotlist = list()
for(u in selected_users){
  g_u = plot_hsmm_seq(X = X %>% filter(seq_id == u), 
                      model = R_hsmm, 
                      title = paste0("example user ",which(selected_users == u)),
                      compact_view = TRUE, add_color_legend_in_compact_view = FALSE) 
  plotlist[[u]] = g_u 
}

g_example = ggarrange(plotlist = plotlist, ncol = 1, nrow = 2)


## Assembled figures

fig1 = ggarrange(g_app_screen, g_example, ncol = 2, nrow = 1, widths = c(1.1,2), labels = "auto")
fig1

```


# Table 1

```{r}

X = read_feather(path = "../../semiM-Data/Kindara/output_data/processed_app_data.feather")

quantile5 = function(x) quantile(x, probs = 0.05)
quantile25 = function(x) quantile(x, probs = 0.25)
quantile75 = function(x) quantile(x, probs = 0.75)
quantile95 = function(x) quantile(x, probs = 0.95)


table_missing_data = 
  X %>%  group_by(seq_id) %>% 
  summarize(tot = n(),
            days_with_log = sum(!is.na(bleeding)),
            overall_tracking_frequency = days_with_log/tot, 
            days_with_temp = sum(!is.na(temp)),
            temp_tracking_frequency = days_with_temp/tot,
            days_with_mucus = sum(!is.na(mucus)),
            mucus_tracking_frequency = days_with_mucus/tot,
            days_with_LH = sum(!is.na(LH)),
            LH_test_tracking_frequency = days_with_LH/tot,
            days_with_preg = sum(!is.na(preg)),
            pregnancy_test_tracking_frequency = days_with_preg/tot,
            .groups = "drop") %>% 
  summarize(across(ends_with("tracking_frequency"), list(mean = mean, median = median, min = min, `5th percentile` = quantile5, `95th percentile` = quantile95, max = max), .names = "{col}.{fn}")) %>% 
  pivot_longer(., cols = everything(), names_to = c("metric",".value"), names_sep = "\\.") %>% 
  mutate(metric = metric %>% str_replace_all(.,"_"," ") %>% str_to_sentence(.) %>% str_replace(.,"Lh","LH"))

table_missing_data = table_missing_data %>% 
  bind_rows(., 
            
            X %>% group_by(seq_id) %>% 
              mutate(is_tracking = !is.na(bleeding),
                     tracking_stretch_id = cumsum((is_tracking != lag(is_tracking)) %>% replace_na(FALSE))) %>% 
              group_by(seq_id, tracking_stretch_id, is_tracking) %>% 
              summarize(n = n(), .groups = "drop") %>% 
              group_by(seq_id, is_tracking) %>% 
              summarize(N = max(n), .groups = "drop") %>% 
              group_by(is_tracking) %>% 
              summarize(
                across(
                  N, 
                  list(mean = mean, median = median,  min = min, `5th percentile` = quantile5, `95th percentile` = quantile95, max = max), 
                  .names = "{fn}"), 
                .groups = "drop") %>% 
              mutate(metric = ifelse(is_tracking, "Longest consecutive tracking (days)", "Longest consecutive missing (days)")) %>% 
              select(-is_tracking) 
            
  )

table_missing_data

save(table_missing_data, 
     file = "../Figures_Tables_Media/Tables/Kindara/table_missing_data.Rdata")

```


# Figure 2

```{r fig2, fig.width=9, fig.height=9}

# Tracking model

tracking_model = image_read("../Figures_Tables_Media/Media/tracking_model-02.png")

tracking_model_ratio = image_info(tracking_model)$height / image_info(tracking_model)$width 
padding = 20

g_tm = 
  ggplot() + 
  coord_fixed(ratio = tracking_model_ratio) +
  background_image(tracking_model) + 
  theme(plot.margin = 
          ggplot2::margin(t = padding, l = padding, r = padding, b = padding, unit = "pt"))


# hierarchical approach
h_method = image_read("../Figures_Tables_Media/Media/tracking_model-04.png")

h_method_ratio = image_info(h_method)$height / image_info(h_method)$width 

g_hm = ggplot() + 
  coord_fixed(ratio = h_method_ratio) +
  background_image(h_method) + 
  theme(plot.margin = ggplot2::margin(t = padding, l = padding, r = padding, b = padding, unit = "pt"))


# R_hsmm graph


load("../Data/models/R_hsmm.Rdata", verbose = TRUE)
load("../Data/models/R_model.Rdata", verbose = TRUE)

set.seed(17) # 2, 10
g_model_graph = plot_hsmm_transitions(model = R_hsmm, size = 10) + theme(aspect.ratio = NULL) 


# R_hsmm sojourn

sojourn = as.data.frame(t(R_model$sojourn))
colnames(sojourn) = R_model$states$abbr
sojourn$day = 1:nrow(sojourn)
sojourn_long = pivot_longer(sojourn, cols = -day, names_to = "State", values_to = "d")

sojourn_long = sojourn_long %>% 
  mutate(
    color = R_model$states$colors[match(State, R_model$states$abbr)],
    group = R_model$states$group_sojourn_time_scale[match(State,R_model$states$abbr)]  %>% str_c(.," states") %>% 
      factor(.,levels = unique(R_model$states$group_sojourn_time_scale) %>% str_c(.," states")) 
  ) %>% arrange(group, State) %>% 
  mutate(color = factor(color, levels = unique(color)),
         State = factor(State, levels = R_model$states$abbr))

g_sojourn_1 = ggplot(sojourn_long %>% filter(State %in% c("M","lE","hE","Lut", "Ano", "P"), day < 30), aes(x = day, y = d, fill = color, col = color))+
  geom_area(position = "identity", alpha = 0.5)+
  scale_color_identity() + scale_fill_identity() +
  expand_limits(x = 0) +
  scale_x_continuous(breaks = seq(0,28, by = 7), minor_breaks = NULL)+
  ylab("pdf") + xlab("days")+
  facet_grid(State ~ ., scale = "free") +
  theme_set(theme_minimal()) +
  theme(strip.background = element_rect(fill = "gray80", color = NA))


g_sojourn_2 = ggplot(sojourn_long %>% filter(State %in% c("P","L", "B"), day < 30), aes(x = day, y = d, fill = color, col = color))+
  geom_area(position = "identity", alpha = 0.5)+
  scale_color_identity() + scale_fill_identity() +
  expand_limits(x = 0) +
  scale_x_continuous(breaks = seq(0,150, by = 7))+
  ylab("pdf") + xlab("days")+
  facet_grid(State ~ ., scale = "free") +
  theme_set(theme_minimal())


g_sojourn_3 = ggplot(
  sojourn_long %>% 
    filter(State %in% c("AB", "PL","PB3","B", "PP","BF"), day <= 150), 
  aes(x = day/7, y = d, fill = color, col = color))+
  geom_area(position = "identity", alpha = 0.5)+
  scale_color_identity() + scale_fill_identity() +
  expand_limits(x = 0) +
  scale_x_continuous(breaks = seq(0,21, by = 2), minor_breaks = 0:21)+
  ylab("pdf") + xlab("weeks")+
  facet_grid(State ~ ., scale = "free") +
  theme_set(theme_minimal()) +
  theme(strip.background = element_rect(fill = "gray80", color = NA))

g_sojourn = ggarrange(g_sojourn_1, g_sojourn_3, ncol = 2, nrow = 1, widths = c(1,1.4))


# T_hsmm graph

# load("../Data/models/T_hsmm.Rdata", verbose = TRUE)
# 
# g_T = plot_hsmm_transitions(model = T_hsmm, size = 20, label_size = 0.3*20/2, arrow_gap = 0.1, label_color = "white") +
#   scale_y_continuous(expand = expansion(add = 0.2)) +
#   scale_x_continuous(expand = expansion(add = 0.2))

# ASSEMBLE FIGURE TOGETHER

set.seed(17) # 2, 10
fig2 = ggarrange(g_model_graph, g_sojourn , g_tm, g_hm,  ncol = 2, nrow = 2, labels = "auto", heights = c(1, 1), widths = c(1.2,1))
fig2


```



```{r fig2-R-model-figure, eval = FALSE, echo = FALSE, results = "hide", warning=FALSE, fig.width=10, fig.height=10, out.width='100%', fig.cap=" (b)  (c) Initial marginal distributions in each state."}


# marginal emission distributions
# 
# g_marg_em = plot_hsmm_marg_dist(model = R_hsmm, show_missing_probs = FALSE) + guides(alpha = FALSE) +
#   theme(panel.spacing.x = unit(10,unit = "pt"))
# 
# rm(g_sojourn_1, g_sojourn_2, g_sojourn_3)
# 
# 
# # ASSEMBLING FIGURE TOGETHER
# 
# fig2 = ggarrange(
#   ggarrange(g_model_graph, g_sojourn, ncol = 1, nrow = 2, labels = "auto"),
#   g_marg_em + ggtitle("") + theme(axis.title.x = element_blank()), 
#   labels = c("", "c"),
#   ncol = 2, nrow = 1
# )
# 
# fig2

```



# Figure 3


```{r fig3, echo = FALSE, warning=FALSE, fig.width=10, fig.height=10}


# accuracies
accuracies = read_feather(path = "../Data/decodings/rw_accuracies.feather")

g_acc = 
  ggplot(accuracies %>% 
           mutate(
             #accuracy_type = accuracy_type %>% str_replace(" ","\n"),
             type = type %>% str_replace("specified","spec.")), 
         aes(y = value, x = type, fill = accuracy_type))+
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(. ~ model_name) +
  xlab("") +
  ylab("(weighted mean of sample)\naccuracy") +
  scale_y_continuous(breaks = seq(0,1,by = 0.2), minor_breaks = seq(0,1,by = 0.05)) +
  scale_fill_manual("",values = c("darkseagreen2","cornflowerblue")) +
  theme(strip.background = element_rect(fill = "gray85", colour = NA),
        #axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "bottom",
        legend.key.size = rep(unit(10,"pt"),2),
        legend.margin = ggplot2::margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")
  )


# confusion matrices

conf_matrices = read_feather(path = "../Data/decodings/rw_conf_matrices.feather")

g_conf_mat = 
  ggplot(
    conf_matrices %>% filter(type == "specified", proportion_type == "Proportion"), 
    aes(x = decoded_state_name, y = GT_state_name, fill = proportion)) +
  geom_tile() + 
  facet_wrap(model_name ~ ., ncol = 2) +
  scale_fill_gradient(
    "Proportion of time-points    \nwith a given manual label    ", 
    low = "white", high = "steelblue4", limits = c(0,1)) +
  coord_fixed() +
  ylab("Manually labelled states") + xlab("Decoded states")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        strip.background = element_rect(fill = "gray85", colour = NA),
        legend.key.height = unit(10,"pt"),
        legend.title = element_text(vjust = 0.9),
        legend.margin = ggplot2::margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"),
        legend.position = "bottom")

# pregnancy durations

pregnancies = read_feather(path = "../Data/decodings/pregnancies.feather")

g_preg = 
  ggplot(pregnancies %>% filter(str_detect(type, "pregnancy"), model_type == "specified") ,  
         # %>% mutate(type = type %>%  str_replace(.," ","\n"))
         aes(x = duration/7, fill = type)) +
  geom_histogram(position = "identity", binwidth = 1, alpha = 0.85) +
  geom_vline(xintercept = c(38,42), linetype = 3, col = "gray") +
  facet_grid(model_name ~ ., scale = "free_y") +
  scale_fill_manual("",values = c("pink3","plum1")) +
  xlab("duration (weeks)") +
  theme(strip.background = element_rect(fill = "gray85", colour = NA),
        strip.text.y = element_text(angle = 0, hjust = 0),
        legend.position = "bottom",
        legend.key.size = rep(unit(10,"pt"),2),
        legend.margin = ggplot2::margin(t = 0, r = 0, b = 0, l = 0, unit = "pt"))


# Examples

X = read_feather(path = str_c(IO$output_data,"X_with_decoding_specified_models.feather"))

g_example = plot_hsmm_seq(X = X %>% filter(seq_id == unique(X$seq_id)[2]) %>%
                            select(-starts_with("state_prob_")), # 2 8 
                          model = R_hsmm, compact_view = TRUE,
                          add_color_legend_in_compact_view = FALSE,
                          title = " ")



# ASSEMBLING FIGURE

g_ac = ggarrange(g_acc, g_preg, ncol = 1, labels = c("a","c"))
g_abc = ggarrange(g_ac, g_conf_mat, ncol = 2, labels = c("","b"), widths = c(1,1.15))


fig3 = 
  ggarrange(
    g_abc,
    g_example,
    ncol = 1, 
    nrow = 2,
    labels = c("","d"),
    heights = c(2,1.2)
  )


fig3

```





# Figure 4



```{r fig4, fig.width=10, fig.height=6.5}

# Simulated sequence with decoding
X = read_feather(path = "../../semiM-Public-Repo/Data/synthetic_data/Xsim.feather")
RES = read_feather(path = "../../semiM-Public-Repo/Data/decodings/RES_synthetic_data.feather")

Xb = left_join(X %>% 
                 select(seq_id, t, bleeding, LH, mucus, temp, preg, state) %>%
                 rename(state_ground_truth = state),
               RES %>% 
                 select(seq_id, t, state, prob) %>%  
                 rename(state_decoded = state, prob_state_decoded = prob),
               by = c("seq_id","t"))

g_example = plot_hsmm_seq(X = Xb %>% filter(seq_id == 13), # 3, 7
                          model = R_hsmm, 
                          compact_view = TRUE,
                          add_color_legend_in_compact_view = FALSE,
                          title = " ") # Labeling of a simulated sequence.

# performances
load("../../semiM-Public-Repo/Data/plots/g_synth_acc.Rdata")
g_synth_acc  = g_synth_acc + 
  theme(strip.background.x = element_rect(fill = "gray80", colour = NA))

# confusion matrix

load("../../semiM-Public-Repo/Data/plots/g_synth_conf_mat.Rdata")

# per-state accuracy
load("../../semiM-Public-Repo/Data/plots/g_synth_acc_per_state2.Rdata")
g_synth_acc_per_state2 = g_synth_acc_per_state2 + 
  theme(strip.background.x = element_rect(fill = "gray80", colour = NA))


fig4 = ggarrange(
  g_example,
  ggarrange(g_synth_acc, g_synth_acc_per_state2, 
            ncol = 2, nrow = 1, widths = c(1.2,4), labels = c("b","c"),
            align = "h", 
            common.legend = TRUE, legend = "bottom"),
  ncol = 1, 
  nrow = 2,
  labels = c("a",""),
  heights = c(1.4,1.2)
)

fig4

```




# Save figures

```{r export-figures}

fig_path = "../Figures_Tables_Media/Figures/"
scale = 1.3

fig1_file = str_c(fig_path, "fig1.png")
ggsave(fig1_file,
       plot = fig1,
       width = 18, height = 10, units = "cm",
       dpi = 300,
       scale = scale)

fig2_file = str_c(fig_path, "fig2.png")
ggsave(fig2_file,
       plot = fig2,
       width = 18, height = 15, units = "cm",
       dpi = 300,
       scale = scale)

fig3_file = str_c(fig_path, "fig3.png")
ggsave(fig3_file,
       plot = fig3,
       width = 18, height = 18, units = "cm",
       dpi = 300,
       scale = scale)

fig4_file = str_c(fig_path, "fig4.png")
ggsave(fig4_file,
       plot = fig4,
       width = 18, height = 11, units = "cm",
       dpi = 300,
       scale = scale)


```

```{r export-figures-tiff}

fig1_file = str_c(fig_path, "fig1.pdf")
ggsave(fig1_file,
       plot = fig1,
       width = 18, height = 10, units = "cm",
       dpi = 300,
       scale = scale)

fig2_file = str_c(fig_path, "fig2.pdf")
ggsave(fig2_file,
       plot = fig2,
       width = 18, height = 15, units = "cm",
       dpi = 300,
       scale = scale)

fig3_file = str_c(fig_path, "fig3.pdf")
ggsave(fig3_file,
       plot = fig3,
       width = 18, height = 18, units = "cm",
       dpi = 300,
       scale = scale)

fig4_file = str_c(fig_path, "fig4.pdf")
ggsave(fig4_file,
       plot = fig4,
       width = 18, height = 11, units = "cm",
       dpi = 300,
       scale = scale)
```



